import { createPinia } from "pinia";
import { createApp } from "vue";
import "./styles/demo.scss";
import "./styles/library.scss";
import App from "./App.vue";
import { registerPrintDesignerUi } from "./print-designer/ui/index.js";
const app = createApp(App) as any;
app.use(createPinia());
registerPrintDesignerUi(app);
app.mount("#app");
